package com.github.breadmoirai.discordtabletop.core.games.frosthaven.item

object FHItems {
    private val endpoint = "https://github.com/any2cards/worldhaven/raw/master/images/items/frosthaven"
    val startingItems by lazy { getItems(0..10) }
    val randomItems by lazy { getItems(168..192) }
    val randomBlueprints by lazy { getItems(51..65) }
    val randomStartingBlueprints by lazy { getItems(51..58) }

    fun startingDeck(id: String): FHItemDeck {
        return FHItemDeck(id, startingItems, randomItems, randomStartingBlueprints)
    }

    fun getItems(range: IntRange): List<FHItem> {
        val adjRange = if (245 in range) {
            range.first..range.last + 3
        } else range
        return ITEMS.subList(adjRange.first - 1, adjRange.last)
    }

    // @formatter:off
    val ITEMS = listOf(
        FHItem("1",    "Spyglass",                FHItemSlot.Head,    "$endpoint/001-010/fh-001-spyglass.png"),
        FHItem("2",    "Crude Helmet",            FHItemSlot.Head,    "$endpoint/001-010/fh-002-crude-helmet.png"),
        FHItem("3",    "Traveling Cloak",         FHItemSlot.Body,    "$endpoint/001-010/fh-003-traveling-cloak.png"),
        FHItem("4",    "Crude Hide Armor",        FHItemSlot.Body,    "$endpoint/001-010/fh-004-crude-hide-armor.png"),
        FHItem("5",    "Crude Boots",             FHItemSlot.Legs,    "$endpoint/001-010/fh-005-crude-boots.png"),
        FHItem("6",    "Flexible Slippers",       FHItemSlot.Legs,    "$endpoint/001-010/fh-006-flexible-slippers.png"),
        FHItem("7",    "Crude Bow",               FHItemSlot.TwoHand, "$endpoint/001-010/fh-007-crude-bow.png"),
        FHItem("8",    "Crude Spear",             FHItemSlot.TwoHand, "$endpoint/001-010/fh-008-crude-spear.png"),
        FHItem("9",    "Protective Scepter",      FHItemSlot.OneHand, "$endpoint/001-010/fh-009-protective-scepter.png"),
        FHItem("10",   "Crude Shield",            FHItemSlot.OneHand, "$endpoint/001-010/fh-010-crude-shield.png"),
        FHItem("11",   "Simple Charm",            FHItemSlot.Head,    "$endpoint/011-015/fh-011-simple-charm.png"),
        FHItem("12",   "Crude Chain Armor",       FHItemSlot.Body,    "$endpoint/011-015/fh-012-crude-chain-armor.png"),
        FHItem("13",   "Dancing Slippers",        FHItemSlot.Legs,    "$endpoint/011-015/fh-013-dancing-slippers.png"),
        FHItem("14",   "Heavy Sword",             FHItemSlot.OneHand, "$endpoint/011-015/fh-014-heavy-sword.png"),
        FHItem("15",   "Reinforced Shield",       FHItemSlot.OneHand, "$endpoint/011-015/fh-015-reinforced-shield.png"),
        FHItem("16",   "Inspiring Helmet",        FHItemSlot.Head,    "$endpoint/016-020/fh-016-inspiring-helmet.png"),
        FHItem("17",   "Cured Leather Armor",     FHItemSlot.Body,    "$endpoint/016-020/fh-017-cured-leather-armor.png"),
        FHItem("18",   "Rough Boots",             FHItemSlot.Legs,    "$endpoint/016-020/fh-018-rough-boots.png"),
        FHItem("19",   "Ringing Hammer",          FHItemSlot.OneHand, "$endpoint/016-020/fh-019-ringing-hammer.png"),
        FHItem("20",   "Well Strung Bow",         FHItemSlot.TwoHand, "$endpoint/016-020/fh-020-well-strung-bow.png"),
        FHItem("21",   "Chain Hood",              FHItemSlot.Head,    "$endpoint/021-025/fh-021-chain-hood.png"),
        FHItem("22",   "Heavy Chain Armor",       FHItemSlot.Body,    "$endpoint/021-025/fh-022-heavy-chain-armor.png"),
        FHItem("23",   "Sturdy Greaves",          FHItemSlot.Legs,    "$endpoint/021-025/fh-023-sturdy-greaves.png"),
        FHItem("24",   "Corrupted Blade",         FHItemSlot.OneHand, "$endpoint/021-025/fh-024-corrupted-blade.png"),
        FHItem("25",   "Soothing Scepter",        FHItemSlot.OneHand, "$endpoint/021-025/fh-025-soothing-scepter.png"),
        FHItem("26",   "Truesight Lenses",        FHItemSlot.Head,    "$endpoint/026-030/fh-026-truesight-lenses.png"),
        FHItem("27",   "Cloak Of Warding",        FHItemSlot.Body,    "$endpoint/026-030/fh-027-cloak-of-warding.png"),
        FHItem("28",   "Sturdy Boots",            FHItemSlot.Legs,    "$endpoint/026-030/fh-028-sturdy-boots.png"),
        FHItem("29",   "Cleaving Axe",            FHItemSlot.TwoHand, "$endpoint/026-030/fh-029-cleaving-axe.png"),
        FHItem("30",   "Parrying Gauntlet",       FHItemSlot.OneHand, "$endpoint/026-030/fh-030-parrying-gauntlet.png"),
        FHItem("31",   "Deathproof Charm",        FHItemSlot.Head,    "$endpoint/031-035/fh-031-deathproof-charm.png"),
        FHItem("32",   "Shell Armor",             FHItemSlot.Body,    "$endpoint/031-035/fh-032-shell-armor.png"),
        FHItem("33",   "Volatile Boots",          FHItemSlot.Legs,    "$endpoint/031-035/fh-033-volatile-boots.png"),
        FHItem("34",   "Shrapnel Bomb",           FHItemSlot.OneHand, "$endpoint/031-035/fh-034-shrapnel-bomb.png"),
        FHItem("35",   "Kite Shield",             FHItemSlot.OneHand, "$endpoint/031-035/fh-035-kite-shield.png"),
        FHItem("36",   "Plumed Helmet",           FHItemSlot.Head,    "$endpoint/036-040/fh-036-plumed-helmet.png"),
        FHItem("37",   "Ghost Cloak",             FHItemSlot.Body,    "$endpoint/036-040/fh-037-ghost-cloak.png"),
        FHItem("38",   "Duelist's Shoes",         FHItemSlot.Legs,    "$endpoint/036-040/fh-038-duelists-shoes.png"),
        FHItem("39",   "Abyss Axe",               FHItemSlot.TwoHand, "$endpoint/036-040/fh-039-abyss-axe.png"),
        FHItem("40",   "Heartstrike Bow",         FHItemSlot.TwoHand, "$endpoint/036-040/fh-040-heartstrike-bow.png"),
        FHItem("41",   "Intricate Charm",         FHItemSlot.Head,    "$endpoint/041-045/fh-041-intricate-charm.png"),
        FHItem("42",   "Ornate Armor",            FHItemSlot.Body,    "$endpoint/041-045/fh-042-ornate-armor.png"),
        FHItem("43",   "Kicking Boots",           FHItemSlot.Legs,    "$endpoint/041-045/fh-043-kicking-boots.png"),
        FHItem("44",   "Sword Of Absolution",     FHItemSlot.OneHand, "$endpoint/041-045/fh-044-sword-of-absolution.png"),
        FHItem("45",   "Master Scepter",          FHItemSlot.OneHand, "$endpoint/041-045/fh-045-master-scepter.png"),
        FHItem("46",   "Double Lens Goggles",     FHItemSlot.Head,    "$endpoint/046-050/fh-046-double-lens-goggles.png"),
        FHItem("47",   "Robes Of Doom",           FHItemSlot.Body,    "$endpoint/046-050/fh-047-robes-of-doom.png"),
        FHItem("48",   "Living Shoes",            FHItemSlot.Legs,    "$endpoint/046-050/fh-048-living-shoes.png"),
        FHItem("49",   "Cruel Dagger",            FHItemSlot.OneHand, "$endpoint/046-050/fh-049-cruel-dagger.png"),
        FHItem("50",   "Shield Of Reciprocity",   FHItemSlot.OneHand, "$endpoint/046-050/fh-050-shield-of-reciprocity.png"),
        FHItem("51",   "Spiked Collar",           FHItemSlot.Head,    "$endpoint/051-065/fh-051a-spiked-collar.png"),
        FHItem("52",   "Laser Lens",              FHItemSlot.Head,    "$endpoint/051-065/fh-052a-laser-lens.png"),
        FHItem("53",   "Hobnail Boots",           FHItemSlot.Legs,    "$endpoint/051-065/fh-053a-hobnail-boots.png"),
        FHItem("54",   "Restful Slippers",        FHItemSlot.Legs,    "$endpoint/051-065/fh-054a-restful-slippers.png"),
        FHItem("55",   "Biting Gauntlet",         FHItemSlot.OneHand, "$endpoint/051-065/fh-055a-biting-gauntlet.png"),
        FHItem("56",   "Scavenger's Magnet",      FHItemSlot.OneHand, "$endpoint/051-065/fh-056a-scavengers-magnet.png"),
        FHItem("57",   "Shovel",                  FHItemSlot.OneHand, "$endpoint/051-065/fh-057a-shovel.png"),
        FHItem("58",   "Slippery Sword",          FHItemSlot.OneHand, "$endpoint/051-065/fh-058a-slippery-sword.png"),
        FHItem("59",   "Charm Of Expertise",      FHItemSlot.Head,    "$endpoint/051-065/fh-059a-charm-of-expertise.png"),
        FHItem("60",   "Cloak Of Many Pockets",   FHItemSlot.Body,    "$endpoint/051-065/fh-060a-cloak-of-many-pockets.png"),
        FHItem("61",   "Spiked Shell",            FHItemSlot.Body,    "$endpoint/051-065/fh-061a-spiked-shell.png"),
        FHItem("62",   "Everlasting Boots",       FHItemSlot.Legs,    "$endpoint/051-065/fh-062a-everlasting-boots.png"),
        FHItem("63",   "Shadow Stompers",         FHItemSlot.Legs,    "$endpoint/051-065/fh-063a-shadow-stompers.png"),
        FHItem("64",   "Detonator",               FHItemSlot.OneHand, "$endpoint/051-065/fh-064a-detonator.png"),
        FHItem("65",   "Rust Powder",             FHItemSlot.Bag,     "$endpoint/051-065/fh-065a-rust-powder.png"),
        FHItem("66",   "Amulet Of Eternal Life",  FHItemSlot.Head,    "$endpoint/066-082/fh-066-amulet-of-eternal-life.png"),
        FHItem("67",   "Converging Lenses",       FHItemSlot.Head,    "$endpoint/066-082/fh-067-converging-lenses.png"),
        FHItem("68",   "Scaled Armor",            FHItemSlot.Body,    "$endpoint/066-082/fh-068-scaled-armor.png"),
        FHItem("69",   "Feathered Cloak",         FHItemSlot.Body,    "$endpoint/066-082/fh-069-feathered-cloak.png"),
        FHItem("70",   "Aesther Robe",            FHItemSlot.Body,    "$endpoint/066-082/fh-070-aesther-robe.png"),
        FHItem("71",   "Bone Boots",              FHItemSlot.Legs,    "$endpoint/066-082/fh-071-bone-boots.png"),
        FHItem("72",   "Oak Staff",               FHItemSlot.TwoHand, "$endpoint/066-082/fh-072-oak-staff.png"),
        FHItem("73",   "Energizing Baton",        FHItemSlot.OneHand, "$endpoint/066-082/fh-073-energizing-baton.png"),
        FHItem("74",   "Shock Grenades",          FHItemSlot.OneHand, "$endpoint/066-082/fh-074-shock-grenades.png"),
        FHItem("75",   "Rose Gauntlet",           FHItemSlot.OneHand, "$endpoint/066-082/fh-075-rose-gauntlet.png"),
        FHItem("76",   "Horn Of Command",         FHItemSlot.OneHand, "$endpoint/066-082/fh-076-horn-of-command.png"),
        FHItem("77",   "Chaos Cannon",            FHItemSlot.OneHand, "$endpoint/066-082/fh-077-chaos-cannon.png"),
        FHItem("78",   "Balanced Scales",         FHItemSlot.OneHand, "$endpoint/066-082/fh-078-balanced-scales.png"),
        FHItem("79",   "Roasted Fowl",            FHItemSlot.Bag,     "$endpoint/066-082/fh-079-roasted-fowl.png"),
        FHItem("80",   "Living Stone",            FHItemSlot.Bag,     "$endpoint/066-082/fh-080-living-stone.png"),
        FHItem("81",   "Pain Simulacrum",         FHItemSlot.Bag,     "$endpoint/066-082/fh-081-pain-simulacrum.png"),
        FHItem("82",   "Mechanical Cube",         FHItemSlot.Bag,     "$endpoint/066-082/fh-082-mechanical-cube.png"),
        FHItem("83",   "Healing Potion",          FHItemSlot.Bag,     "$endpoint/083-119/fh-083-healing-potion.png"),
        FHItem("84",   "Stamina Potion",          FHItemSlot.Bag,     "$endpoint/083-119/fh-084-stamina-potion.png"),
        FHItem("85",   "Power Potion",            FHItemSlot.Bag,     "$endpoint/083-119/fh-085-power-potion.png"),
        FHItem("86",   "Element Potion",          FHItemSlot.Bag,     "$endpoint/083-119/fh-086-element-potion.png"),
        FHItem("87",   "Cure Potion",             FHItemSlot.Bag,     "$endpoint/083-119/fh-087-cure-potion.png"),
        FHItem("88",   "Fireshield Potion",       FHItemSlot.Bag,     "$endpoint/083-119/fh-088-fireshield-potion.png"),
        FHItem("89",   "Stoneskin Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-089-stoneskin-potion.png"),
        FHItem("90",   "Muscle Potion",           FHItemSlot.Bag,     "$endpoint/083-119/fh-090-muscle-potion.png"),
        FHItem("91",   "Holy Water",              FHItemSlot.Bag,     "$endpoint/083-119/fh-091-holy-water.png"),
        FHItem("92",   "Renewing Potion",         FHItemSlot.Bag,     "$endpoint/083-119/fh-092-renewing-potion.png"),
        FHItem("93",   "Glancing Potion",         FHItemSlot.Bag,     "$endpoint/083-119/fh-093-glancing-potion.png"),
        FHItem("94",   "Frenzy Potion",           FHItemSlot.Bag,     "$endpoint/083-119/fh-094-frenzy-potion.png"),
        FHItem("95",   "Poison Vial",             FHItemSlot.Bag,     "$endpoint/083-119/fh-095-poison-vial.png"),
        FHItem("96",   "Flame Vial",              FHItemSlot.Bag,     "$endpoint/083-119/fh-096-flame-vial.png"),
        FHItem("97",   "Explosive Vial",          FHItemSlot.Bag,     "$endpoint/083-119/fh-097-explosive-vial.png"),
        FHItem("98",   "Unhealthy Mixture",       FHItemSlot.Bag,     "$endpoint/083-119/fh-098-unhealthy-mixture.png"),
        FHItem("99",   "Major Healing Potion",    FHItemSlot.Bag,     "$endpoint/083-119/fh-099-major-healing-potion.png"),
        FHItem("100",  "Major Stamina Potion",    FHItemSlot.Bag,     "$endpoint/083-119/fh-100-major-stamina-potion.png"),
        FHItem("101",  "Major Power Potion",      FHItemSlot.Bag,     "$endpoint/083-119/fh-101-major-power-potion.png"),
        FHItem("102",  "Major Element Potion",    FHItemSlot.Bag,     "$endpoint/083-119/fh-102-major-element-potion.png"),
        FHItem("103",  "Major Cure Potion",       FHItemSlot.Bag,     "$endpoint/083-119/fh-103-major-cure-potion.png"),
        FHItem("104",  "Swiftness Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-104-swiftness-potion.png"),
        FHItem("105",  "Major Fireshield Potion", FHItemSlot.Bag,     "$endpoint/083-119/fh-105-major-fireshield-potion.png"),
        FHItem("106",  "Stonewall Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-106-stonewall-potion.png"),
        FHItem("107",  "Vigor Potion",            FHItemSlot.Bag,     "$endpoint/083-119/fh-107-vigor-potion.png"),
        FHItem("108",  "Holy Rain",               FHItemSlot.Bag,     "$endpoint/083-119/fh-108-holy-rain.png"),
        FHItem("109",  "Major Renewing Potion",   FHItemSlot.Bag,     "$endpoint/083-119/fh-109-major-renewing-potion.png"),
        FHItem("110",  "Precision Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-110-precision-potion.png"),
        FHItem("111",  "Major Frenzy Potion",     FHItemSlot.Bag,     "$endpoint/083-119/fh-111-major-frenzy-potion.png"),
        FHItem("112",  "Hammer Potion",           FHItemSlot.Bag,     "$endpoint/083-119/fh-112-hammer-potion.png"),
        FHItem("113",  "Expertise Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-113-expertise-potion.png"),
        FHItem("114",  "Foresight Potion",        FHItemSlot.Bag,     "$endpoint/083-119/fh-114-foresight-potion.png"),
        FHItem("115",  "Infusion Potion",         FHItemSlot.Bag,     "$endpoint/083-119/fh-115-infusion-potion.png"),
        FHItem("116",  "Plague Flask",            FHItemSlot.Bag,     "$endpoint/083-119/fh-116-plague-flask.png"),
        FHItem("117",  "Inferno Flask",           FHItemSlot.Bag,     "$endpoint/083-119/fh-117-inferno-flask.png"),
        FHItem("118",  "Fulminant Flask",         FHItemSlot.Bag,     "$endpoint/083-119/fh-118-fulminant-flask.png"),
        FHItem("119",  "Deadly Mixture",          FHItemSlot.Bag,     "$endpoint/083-119/fh-119-deadly-mixture.png"),
        FHItem("120",  "Amulet Of Life",          FHItemSlot.Head,    "$endpoint/120-128/fh-120-amulet-of-life.png"),
        FHItem("121",  "Circlet Of Elements",     FHItemSlot.Head,    "$endpoint/120-128/fh-121-circlet-of-elements.png"),
        FHItem("122",  "Warden's Robes",          FHItemSlot.Body,    "$endpoint/120-128/fh-122-wardens-robes.png"),
        FHItem("123",  "Leather Armor",           FHItemSlot.Body,    "$endpoint/120-128/fh-123-leather-armor.png"),
        FHItem("124",  "Winged Shoes",            FHItemSlot.Legs,    "$endpoint/120-128/fh-124-winged-shoes.png"),
        FHItem("125",  "Boots Of Speed",          FHItemSlot.Legs,    "$endpoint/120-128/fh-125-boots-of-speed.png"),
        FHItem("126",  "Weighted Net",            FHItemSlot.TwoHand, "$endpoint/120-128/fh-126-weighted-net.png"),
        FHItem("127",  "Poison Dagger",           FHItemSlot.OneHand, "$endpoint/120-128/fh-127-poison-dagger.png"),
        FHItem("128",  "Heater Shield",           FHItemSlot.OneHand, "$endpoint/120-128/fh-128-heater-shield.png"),
        FHItem("129",  "Eagle Eye Goggles",       FHItemSlot.Head,    "$endpoint/129-167/fh-129-eagle-eye-goggles.png"),
        FHItem("130",  "Iron Helmet",             FHItemSlot.Head,    "$endpoint/129-167/fh-130-iron-helmet.png"),
        FHItem("131",  "Chainmail",               FHItemSlot.Body,    "$endpoint/129-167/fh-131-chainmail.png"),
        FHItem("132",  "Cloak Of Pockets",        FHItemSlot.Body,    "$endpoint/129-167/fh-132-cloak-of-pockets.png"),
        FHItem("133",  "Nimble Legguards",        FHItemSlot.Legs,    "$endpoint/129-167/fh-133-nimble-legguards.png"),
        FHItem("134",  "Comfortable Shoes",       FHItemSlot.Legs,    "$endpoint/129-167/fh-134-comfortable-shoes.png"),
        FHItem("135",  "Armorbane Bow",           FHItemSlot.TwoHand, "$endpoint/129-167/fh-135-armorbane-bow.png"),
        FHItem("136",  "Battle Axe",              FHItemSlot.TwoHand, "$endpoint/129-167/fh-136-battle-axe.png"),
        FHItem("137",  "Tower Shield",            FHItemSlot.OneHand, "$endpoint/129-167/fh-137-tower-shield.png"),
        FHItem("138",  "Heavy Basinet",           FHItemSlot.Head,    "$endpoint/129-167/fh-138-heavy-basinet.png"),
        FHItem("139",  "Horned Helm",             FHItemSlot.Head,    "$endpoint/129-167/fh-139-horned-helm.png"),
        FHItem("140",  "Mantle Of Summoning",     FHItemSlot.Body,    "$endpoint/129-167/fh-140-mantle-of-summoning.png"),
        FHItem("141",  "Studded Leather",         FHItemSlot.Body,    "$endpoint/129-167/fh-141-studded-leather.png"),
        FHItem("142",  "Boots Of Quickness",      FHItemSlot.Legs,    "$endpoint/129-167/fh-142-boots-of-quickness.png"),
        FHItem("143",  "Endurance Footwraps",     FHItemSlot.Legs,    "$endpoint/129-167/fh-143-endurance-footwraps.png"),
        FHItem("144",  "Staff Of Eminence",       FHItemSlot.TwoHand, "$endpoint/129-167/fh-144-staff-of-eminence.png"),
        FHItem("145",  "Versatile Dagger",        FHItemSlot.OneHand, "$endpoint/129-167/fh-145-versatile-dagger.png"),
        FHItem("146",  "Hooked Chain",            FHItemSlot.TwoHand, "$endpoint/129-167/fh-146-hooked-chain.png"),
        FHItem("147",  "Mask Of Terror",          FHItemSlot.Head,    "$endpoint/129-167/fh-147-mask-of-terror.png"),
        FHItem("148",  "Circlet Of Sanctity",     FHItemSlot.Head,    "$endpoint/129-167/fh-148-circlet-of-sanctity.png"),
        FHItem("149",  "Platemail",               FHItemSlot.Body,    "$endpoint/129-167/fh-149-platemail.png"),
        FHItem("150",  "Robes Of The Oak",        FHItemSlot.Body,    "$endpoint/129-167/fh-150-robes-of-the-oak.png"),
        FHItem("151",  "Serene Sandals",          FHItemSlot.Legs,    "$endpoint/129-167/fh-151-serene-sandals.png"),
        FHItem("152",  "Steel Sabatons",          FHItemSlot.Legs,    "$endpoint/129-167/fh-152-steel-sabatons.png"),
        FHItem("153",  "Long Spear",              FHItemSlot.TwoHand, "$endpoint/129-167/fh-153-long-spear.png"),
        FHItem("154",  "Volatile Bomb",           FHItemSlot.TwoHand, "$endpoint/129-167/fh-154-volatile-bomb.png"),
        FHItem("155",  "Wall Shield",             FHItemSlot.TwoHand, "$endpoint/129-167/fh-155-wall-shield.png"),
        FHItem("156",  "Moon Earring",            FHItemSlot.Bag,     "$endpoint/129-167/fh-156-moon-earring.png"),
        FHItem("157",  "Steel Ring",              FHItemSlot.Bag,     "$endpoint/129-167/fh-157-steel-ring.png"),
        FHItem("158",  "Deep Earth Brooch",       FHItemSlot.Bag,     "$endpoint/129-167/fh-158-deep-earth-brooch.png"),
        FHItem("159",  "Glorious Bracelet",       FHItemSlot.Bag,     "$endpoint/129-167/fh-159-glorious-bracelet.png"),
        FHItem("160",  "Sun Earring",             FHItemSlot.Bag,     "$endpoint/129-167/fh-160-sun-earring.png"),
        FHItem("161",  "Strategist's Ring",       FHItemSlot.Bag,     "$endpoint/129-167/fh-161-strategists-ring.png"),
        FHItem("162",  "Howling Ice Brooch",      FHItemSlot.Bag,     "$endpoint/129-167/fh-162-howling-ice-brooch.png"),
        FHItem("163",  "Stunning Bracelet",       FHItemSlot.Bag,     "$endpoint/129-167/fh-163-stunning-bracelet.png"),
        FHItem("164",  "Star Earring",            FHItemSlot.Bag,     "$endpoint/129-167/fh-164-star-earring.png"),
        FHItem("165",  "Ring Of Haste",           FHItemSlot.Bag,     "$endpoint/129-167/fh-165-ring-of-haste.png"),
        FHItem("166",  "Blazing Sun Brooch",      FHItemSlot.Bag,     "$endpoint/129-167/fh-166-blazing-sun-brooch.png"),
        FHItem("167",  "Attractive Bracelet",     FHItemSlot.Bag,     "$endpoint/129-167/fh-167-attractive-bracelet.png"),
        FHItem("168",  "Circlet Of Eyes",         FHItemSlot.Head,    "$endpoint/168-192/fh-168-circlet-of-eyes.png"),
        FHItem("169",  "Fateful Charm",           FHItemSlot.Head,    "$endpoint/168-192/fh-169-fateful-charm.png"),
        FHItem("170",  "Eye Of Truth",            FHItemSlot.Head,    "$endpoint/168-192/fh-170-eye-of-truth.png"),
        FHItem("171",  "Rejuvenating Charm",      FHItemSlot.Head,    "$endpoint/168-192/fh-171-rejuvenating-charm.png"),
        FHItem("172",  "Cap Of Premonition",      FHItemSlot.Head,    "$endpoint/168-192/fh-172-cap-of-premonition.png"),
        FHItem("173",  "Multi Colored Cloak",     FHItemSlot.Body,    "$endpoint/168-192/fh-173-multi-colored-cloak.png"),
        FHItem("174",  "Magnetic Cape",           FHItemSlot.Body,    "$endpoint/168-192/fh-174-magnetic-cape.png"),
        FHItem("175",  "Mirrored Armor",          FHItemSlot.Body,    "$endpoint/168-192/fh-175-mirrored-armor.png"),
        FHItem("176",  "Blinking Cape",           FHItemSlot.Body,    "$endpoint/168-192/fh-176-blinking-cape.png"),
        FHItem("177",  "Boots Of Transference",   FHItemSlot.Legs,    "$endpoint/168-192/fh-177-boots-of-transference.png"),
        FHItem("178",  "Tranquil Shoes",          FHItemSlot.Legs,    "$endpoint/168-192/fh-178-tranquil-shoes.png"),
        FHItem("179",  "Burst Boots",             FHItemSlot.Legs,    "$endpoint/168-192/fh-179-burst-boots.png"),
        FHItem("180",  "Boots Of Greed",          FHItemSlot.Legs,    "$endpoint/168-192/fh-180-boots-of-greed.png"),
        FHItem("181",  "Translocation Rod",       FHItemSlot.TwoHand, "$endpoint/168-192/fh-181-translocation-rod.png"),
        FHItem("182",  "Wing Clippers",           FHItemSlot.TwoHand, "$endpoint/168-192/fh-182-wing-clippers.png"),
        FHItem("183",  "Decanter Of Mists",       FHItemSlot.OneHand, "$endpoint/168-192/fh-183-decanter-of-mists.png"),
        FHItem("184",  "Flashing Axe",            FHItemSlot.OneHand, "$endpoint/168-192/fh-184-flashing-axe.png"),
        FHItem("185",  "Mirrored Knife",          FHItemSlot.OneHand, "$endpoint/168-192/fh-185-mirrored-knife.png"),
        FHItem("186",  "Wild Growth Seeds",       FHItemSlot.Bag,     "$endpoint/168-192/fh-186-wild-growth-seeds.png"),
        FHItem("187",  "Dangerous Gear",          FHItemSlot.Bag,     "$endpoint/168-192/fh-187-dangerous-gear.png"),
        FHItem("188",  "Freezing Crystal",        FHItemSlot.Bag,     "$endpoint/168-192/fh-188-freezing-crystal.png"),
        FHItem("189",  "Ring Of The Night",       FHItemSlot.Bag,     "$endpoint/168-192/fh-189-ring-of-the-night.png"),
        FHItem("190",  "White Card",              FHItemSlot.Bag,     "$endpoint/168-192/fh-190-white-card.png"),
        FHItem("191",  "Corrupted Scroll",        FHItemSlot.Bag,     "$endpoint/168-192/fh-191-corrupted-scroll.png"),
        FHItem("192",  "Enticing Bell",           FHItemSlot.Bag,     "$endpoint/168-192/fh-192-enticing-bell.png"),
        FHItem("193",  "Mind Thieving Helmet",    FHItemSlot.Head,    "$endpoint/193-247/fh-193-mind-thieving-helmet.png"),
        FHItem("194",  "Temporal Amulet",         FHItemSlot.Head,    "$endpoint/193-247/fh-194-temporal-amulet.png"),
        FHItem("195",  "Tri Corner Hat",          FHItemSlot.Head,    "$endpoint/193-247/fh-195-tri-corner-hat.png"),
        FHItem("196",  "Choker Of Sacrifice",     FHItemSlot.Head,    "$endpoint/193-247/fh-196-choker-of-sacrifice.png"),
        FHItem("197",  "Aesther Diadem",          FHItemSlot.Head,    "$endpoint/193-247/fh-197-aesther-diadem.png"),
        FHItem("198",  "Hunter's Necklace",       FHItemSlot.Head,    "$endpoint/193-247/fh-198-hunters-necklace.png"),
        FHItem("199",  "Opulent Shoes",           FHItemSlot.Legs,    "$endpoint/193-247/fh-199-opulent-shoes.png"),
        FHItem("200",  "Eventide Scepter",        FHItemSlot.OneHand, "$endpoint/193-247/fh-200-eventide-scepter.png"),
        FHItem("201",  "Wave Blade",              FHItemSlot.TwoHand, "$endpoint/193-247/fh-201-wave-blade.png"),
        FHItem("202",  "Giant Piranha Pig Spine", FHItemSlot.TwoHand, "$endpoint/193-247/fh-202-giant-piranha-pig-spine.png"),
        FHItem("203",  "Scepter Of Control",      FHItemSlot.OneHand, "$endpoint/193-247/fh-203-scepter-of-control.png"),
        FHItem("204",  "Severed Claw",            FHItemSlot.OneHand, "$endpoint/193-247/fh-204-severed-claw.png"),
        FHItem("205",  "Harpoon",                 FHItemSlot.TwoHand, "$endpoint/193-247/fh-205-harpoon.png"),
        FHItem("206",  "Giant Sword",             FHItemSlot.TwoHand, "$endpoint/193-247/fh-206-giant-sword.png"),
        FHItem("207",  "Fishhook",                FHItemSlot.TwoHand, "$endpoint/193-247/fh-207-fishhook.png"),
        FHItem("208",  "Titan Nail",              FHItemSlot.TwoHand, "$endpoint/193-247/fh-208-titan-nail.png"),
        FHItem("209",  "Sword Of Mastery",        FHItemSlot.TwoHand, "$endpoint/193-247/fh-209-sword-of-mastery.png"),
        FHItem("210",  "Tanjo",                   FHItemSlot.TwoHand, "$endpoint/193-247/fh-210-tanjo.png"),
        FHItem("211",  "Boom Barrel",             FHItemSlot.TwoHand, "$endpoint/193-247/fh-211-boom-barrel.png"),
        FHItem("212",  "Elemental Stone",         FHItemSlot.OneHand, "$endpoint/193-247/fh-212-elemental-stone.png"),
        FHItem("213",  "Key Of Seasons",          FHItemSlot.OneHand, "$endpoint/193-247/fh-213-key-of-seasons.png"),
        FHItem("214",  "Cup Of Ventillion",       FHItemSlot.OneHand, "$endpoint/193-247/fh-214-cup-of-ventillion.png"),
        FHItem("215",  "Befuddling Mug",          FHItemSlot.OneHand, "$endpoint/193-247/fh-215-befuddling-mug.png"),
        FHItem("216",  "Tome Of Elements",        FHItemSlot.OneHand, "$endpoint/193-247/fh-216-tome-of-elements.png"),
        FHItem("217",  "Tome Of Time",            FHItemSlot.OneHand, "$endpoint/193-247/fh-217-tome-of-time.png"),
        FHItem("218",  "Tome Of Life",            FHItemSlot.OneHand, "$endpoint/193-247/fh-218-tome-of-life.png"),
        FHItem("219",  "Tome Of Conflict",        FHItemSlot.OneHand, "$endpoint/193-247/fh-219-tome-of-conflict.png"),
        FHItem("220",  "Belara's Quill",          FHItemSlot.OneHand, "$endpoint/193-247/fh-220-belaras-quill.png"),
        FHItem("221",  "Ice Shiv",                FHItemSlot.OneHand, "$endpoint/193-247/fh-221-ice-shiv.png"),
        FHItem("222",  "Black Box",               FHItemSlot.OneHand, "$endpoint/193-247/fh-222-black-box.png"),
        FHItem("223",  "Lightning Rod",           FHItemSlot.OneHand, "$endpoint/193-247/fh-223-lightning-rod.png"),
        FHItem("224",  "Armor Of Empathy",        FHItemSlot.Body,    "$endpoint/193-247/fh-224-armor-of-empathy.png"),
        FHItem("225",  "Algox Carving",           FHItemSlot.Body,    "$endpoint/193-247/fh-225-algox-carving.png"),
        FHItem("226",  "Unfettered Arm",          FHItemSlot.OneHand, "$endpoint/193-247/fh-226-unfettered-arm.png"),
        FHItem("227",  "Data Drive",              FHItemSlot.OneHand, "$endpoint/193-247/fh-227-data-drive.png"),
        FHItem("228",  "Extendable Pole",         FHItemSlot.OneHand, "$endpoint/193-247/fh-228-extendable-pole.png"),
        FHItem("229",  "Exquisite Map",           FHItemSlot.OneHand, "$endpoint/193-247/fh-229-exquisite-map.png"),
        FHItem("230",  "Examination Glass",       FHItemSlot.OneHand, "$endpoint/193-247/fh-230-examination-glass.png"),
        FHItem("231",  "Skinning Knife",          FHItemSlot.OneHand, "$endpoint/193-247/fh-231-skinning-knife.png"),
        FHItem("232",  "Orchid Wand",             FHItemSlot.OneHand, "$endpoint/193-247/fh-232-orchid-wand.png"),
        FHItem("233",  "Dead Raven",              FHItemSlot.Bag,     "$endpoint/193-247/fh-233-dead-raven.png"),
        FHItem("234",  "Ooze Vial",               FHItemSlot.Bag,     "$endpoint/193-247/fh-234-ooze-vial.png"),
        FHItem("235",  "Small Rat",               FHItemSlot.Bag,     "$endpoint/193-247/fh-235-small-rat.png"),
        FHItem("236",  "Cracked Mirror",          FHItemSlot.Bag,     "$endpoint/193-247/fh-236-cracked-mirror.png"),
        FHItem("237",  "Mesmerizing Seashell",    FHItemSlot.Bag,     "$endpoint/193-247/fh-237-mesmerizing-seashell.png"),
        FHItem("238",  "Cracked Idol",            FHItemSlot.Bag,     "$endpoint/193-247/fh-238-cracked-idol.png"),
        FHItem("239",  "Eye Of The Storm",        FHItemSlot.Bag,     "$endpoint/193-247/fh-239-eye-of-the-storm.png"),
        FHItem("240",  "Demon's Gem",             FHItemSlot.Bag,     "$endpoint/193-247/fh-240-demons-gem.png"),
        FHItem("241",  "Shimmering Powder",       FHItemSlot.Bag,     "$endpoint/193-247/fh-241-shimmering-powder.png"),
        FHItem("242",  "Lucky Dice",              FHItemSlot.Bag,     "$endpoint/193-247/fh-242-lucky-dice.png"),
        FHItem("243",  "Cursed Rock",             FHItemSlot.Bag,     "$endpoint/193-247/fh-243-cursed-rock.png"),
        FHItem("244",  "Ember Energy Source",     FHItemSlot.Bag,     "$endpoint/193-247/fh-244-ember-energy-source.png"),
        FHItem("245a", "Ancient Coin",            FHItemSlot.Plot,    "$endpoint/193-247/fh-245a-ancient-coin.png"),
        FHItem("245b", "Ancient Coin",            FHItemSlot.Plot,    "$endpoint/193-247/fh-245b-ancient-coin.png"),
        FHItem("245c", "Ancient Coin",            FHItemSlot.Plot,    "$endpoint/193-247/fh-245c-ancient-coin.png"),
        FHItem("245d", "Ancient Coin",            FHItemSlot.Plot,    "$endpoint/193-247/fh-245d-ancient-coin.png"),
        FHItem("246",  "Key Card",                FHItemSlot.Plot,    "$endpoint/193-247/fh-246-key-card.png"),
        FHItem("247",  "Trainer's Net",           FHItemSlot.OneHand, "$endpoint/193-247/fh-247-trainers-net.png"),
        FHItem("248",  "Wanderer's Club",         FHItemSlot.OneHand, "$endpoint/248-264/fh-248-wanderers-club.png"),
        FHItem("249",  "Recalibration Trigger",   FHItemSlot.Bag,     "$endpoint/248-264/fh-249-recalibration-trigger.png"),
        FHItem("250",  "Spear Of Justice",        FHItemSlot.OneHand, "$endpoint/248-264/fh-250-spear-of-justice.png"),
        FHItem("251",  "Soul Urn",                FHItemSlot.OneHand, "$endpoint/248-264/fh-251-soul-urn.png"),
        FHItem("252",  "Black Earth Codex",       FHItemSlot.OneHand, "$endpoint/248-264/fh-252-black-earth-codex.png"),
        FHItem("253",  "Mask Of Duality",         FHItemSlot.Head,    "$endpoint/248-264/fh-253-mask-of-duality.png"),
        FHItem("254",  "Ancestral Blade",         FHItemSlot.TwoHand, "$endpoint/248-264/fh-254-ancestral-blade.png"),
        FHItem("255",  "Mountain's Heart",        FHItemSlot.Bag,     "$endpoint/248-264/fh-255-mountains-heart.png"),
        FHItem("256",  "Sonorous Shard",          FHItemSlot.Bag,     "$endpoint/248-264/fh-256-sonorous-shard.png"),
        FHItem("257",  "Sly Camouflage",          FHItemSlot.OneHand, "$endpoint/248-264/fh-257-sly-camouflage.png"),
        FHItem("258",  "Skull Of Agony",          FHItemSlot.Bag,     "$endpoint/248-264/fh-258-skull-of-agony.png"),
        FHItem("259",  "Storm Carving",           FHItemSlot.OneHand, "$endpoint/248-264/fh-259-storm-carving.png"),
        FHItem("260",  "Freezing Orb",            FHItemSlot.OneHand, "$endpoint/248-264/fh-260-freezing-orb.png"),
        FHItem("261",  "Energized Module",        FHItemSlot.Bag,     "$endpoint/248-264/fh-261-energized-module.png"),
        FHItem("262",  "Exhaust Boots",           FHItemSlot.Legs,    "$endpoint/248-264/fh-262-exhaust-boots.png"),
        FHItem("263",  "Warlord's Skull",         FHItemSlot.OneHand, "$endpoint/248-264/fh-263-warlords-skull.png"),
        FHItem("264",  "Spiraled Medallion",      FHItemSlot.Head,    "$endpoint/248-264/fh-264-spiraled-medallion.png")
    )
    // @formatter:on
}