package com.github.breadmoirai.discordtabletop.core.games.frosthaven

import com.github.breadmoirai.discordtabletop.storage.Storable
import com.github.breadmoirai.discordtabletop.storage.StorableId

data class BattleGoal(
    @StorableId val name: String,
    val front: String
) : Storable {
    companion object {
        val BATTLE_GOALS = listOf(
            "accountant",
            "acrobat",
            "ascetic",
            "assassin",
            "assistant",
            "bastion",
            "bully",
            "cleaner",
            "closer",
            "conservator",
            "daredevil",
            "dawdler",
            "diehard",
            "duelist",
            "dynamo",
            "egoist",
            "executioner",
            "exterminator",
            "gambler",
            "hunter",
            "insomniac",
            "layabout",
            "masochist",
            "miser",
            "mugger",
            "opener",
            "optimist",
            "overachiever",
            "pacifist",
            "pauper",
            "peacemonger",
            "pedestrian",
            "perfectionist",
            "pickpocket",
            "pincusion",
            "plebeian",
            "prepper",
            "prohibitionist",
            "promoter",
            "rambler",
            "ravager",
            "recluse",
            "ritualist",
            "sadist",
            "scrambler",
            "shirker",
            "slayer",
            "sleeper",
            "slowpoke",
            "sluggard",
            "specialist",
            "straggler",
            "streamliner",
            "tormentor",
            "vanguard",
            "wallflower",
            "wastrel",
            "weakling",
            "workhorse",
            "zealot",
        ).map { BattleGoal(it, "https://github.com/any2cards/worldhaven/raw/master/images/battle-goals/frosthaven/fh-$it.png") }
    }
}